version: 2

sources:
  - name: sap
    description: Fonte do SAP 
    schema: sap_adw
    tables:
      - name: product    
      - name: productcategory
      - name: productsubcategory
      - name: productinventory
      - name: person
      - name: personcreditcard
      - name: creditcard
      - name: salesorderheader
      - name: customer
      - name: salesorderheadersalesreason
      - name: salesreason
      - name: address
      - name: stateprovince
      - name: salesterritory
      - name: countryregion
      - name: salesorderdetail
      - name: salesperson
      - name: businessentityaddress